apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.dockerhubToken }}
kind: Secret
metadata:
  creationTimestamp: "2020-10-24T20:54:54Z"
  name: dockerhubtoken-{{ .Release.Name }}
  namespace: default
type: kubernetes.io/dockerconfigjson