

node {
    def app
    def commit

    stage('Clone repository') {
        /* Let's make sure we have the repository cloned to our workspace */

        checkout scm
    }

    stage('Build image') {
        /* This builds the actual image; synonymous to
         * docker build on the command line */

        app = docker.build("${env.dockerhub}")
    }

    stage('get git commit hash') {

        commit = sh(returnStdout: true, script: "git rev-parse HEAD").trim()
    }


    stage('Push image') {
        /* Finally, we'll push the image with two tags:
         * First, the incremental build number from Jenkins
         * Second, the 'latest' tag.
         * Pushing multiple tags is cheap, as all the layers are reused. */
        docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-credentials') {
            app.push(commit)
        }
    }

    stage('Dangling Volumes') {
          sh 'docker system prune -af --volumes'
    }


    withKubeConfig([credentialsId: "kubenetes-token",serverUrl: "${env.kubernetes_serverUrl}"])  {
        stage('Kubernetes upgrade') {
            // sh "helm upgrade --install  --set name=${NAME} --set image.tag=${VERSION} --set domain=${DOMAIN} ${NAME} ./helm" 
            sh "helm upgrade --install --set dockerhubToken=${env.dockerhubToken} --set env.DBhostname=${env.webapp_dbUrl} --set env.DBusername=${env.webapp_dbusername} --set env.KAFKAHOST=${env.KAFKAHOST}  --set service.type=${env.servicetype} --set ingress.enabled=${env.ingressenabled} --set ingress.hostserviceName=${env.ingresshostserviceName} --set ingress.secretName=${env.ingresssecretName} --set ingress.hostsAddress=${env.ingresshostsAddress} --set image.repository=${env.dockerhub} --set image.tag=${commit} ${env.webapp_releaseName} ./helm"
        }
        if ("${env.whetherGKE}" == 'true') {
            sh "kubectl apply -f helm/ingress-gke.yaml"
        }
    }
}