---

- name: Get k8s VPC id
  ec2_vpc_net_info:
    profile: "{{ prod_aws_profile }}"
    region: "{{ aws_region }}"
    filters:
      "tag:Name": "{{ k8s_request_vpc_name }}"
  register: k8s_request_vpc_id

# - debug: var=k8s_request_vpc_id

- name: Grab k8s VPC route tables
  ec2_vpc_route_table_info:
    profile: "{{ prod_aws_profile }}"
    region: "{{ aws_region }}"
    filters:
      vpc-id: "{{ k8s_request_vpc_id.vpcs[0].id }}"
      # "association.main": "true"
  register: k8s_route_table

# - debug: var=k8s_route_table

- name: Get rds VPC id
  ec2_vpc_net_info:
    profile: "{{ rds_aws_profile }}"
    region: "{{ aws_region }}"
    filters:
      "tag:Name": "{{ rds_accept_vpc_name }}"
  register: rds_accept_vpc_id

# - debug: var=rds_accept_vpc_id

- name: Grab rds VPC route tables
  ec2_vpc_route_table_info:
    profile: "{{ rds_aws_profile }}"
    region: "{{ aws_region }}"
    filters:
      vpc-id: "{{ rds_accept_vpc_id.vpcs[0].id }}"
  register: rds_route_table

- name: List all vpc peers
  ec2_vpc_peering_facts:
    profile: "{{ rds_aws_profile }}"
    region: "{{ aws_region }}"
    filters:
      status-code: active
  register: all_vpc_peers

- debug: var=all_vpc_peers

- name: delete a local VPC peering Connection in rds account
  ec2_vpc_peer:
    region: "{{ aws_region }}"
    profile: "{{ rds_aws_profile }}"
    peering_id: "{{ all_vpc_peers.result[0].vpc_peering_connection_id }}"
    state: absent
  register: vpc_peer_delete_rds

- name: delete a local VPC peering Connection in k8s account
  ec2_vpc_peer:
    region: "{{ aws_region }}"
    profile: "{{ prod_aws_profile }}"
    peering_id: "{{ all_vpc_peers.result[0].vpc_peering_connection_id }}"
    state: absent
  register: vpc_peer_delete_k8s

- name: delete route for rds vpc route table
  command: aws --region us-east-1 ec2 delete-route --route-table-id {{ rds_route_table.route_tables[0].id }} --destination-cidr-block {{ k8s_request_vpc_id.vpcs[0].cidr_block }}
  environment:
    AWS_PROFILE: "{{ rds_aws_profile }}"

- name: delete route for k8s vpc route table
  command: aws --region us-east-1 ec2 delete-route --route-table-id {{ item.id }} --destination-cidr-block {{ rds_accept_vpc_id.vpcs[0].cidr_block }}
  with_items: "{{ k8s_route_table.route_tables }}"
  environment:
    AWS_PROFILE: "{{ prod_aws_profile }}"