{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/tls-acme: "true"
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.hostsAddress }}
    secretName: {{ .Values.ingress.secretName }}
  rules:
  - host: {{ .Values.ingress.hostsAddress }}
    http:
      paths: 
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.ingress.hostserviceName }}
            port:
              number: 80
{{- end }}
