---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-webapp
  ports:
  - port: 80
    name: http
    targetPort: 3000
  - port: 443
    name: https
    targetPort: 3000
  